### ISSUE TITLE
Animations and persistence

### ISSUE THREAD

**Issue by civilframe** [jbauschatz/Knaves#13]
I'm thinking about how to make cards move between zones in an animated fashion, while persisting the game state to the db (for multiplayer). This way, if your opponent moves a card from one zone to another, you would see it in (more-or-less) realtime.

Perhaps each card should have an X,Y position on the canvas, which is calculated by the zone that card is in. The zone would order cards within it, and assign each card an appropriate X,Y (depending on spacing, the zone's X,Y, etc). Animating a card's movement given X,Y coordinates would be trivial via CSS.

As far as persistence, we wouldn't want to save a card's X,Y to the db (for latency's sake). I think if we just saved the card's parent zone, that would be enough. So when a Card is moved from Zone A to Zone B, we would update it's parent_zone property in the db. Each opponent would receive this update, and their local canvas would recalculate the card's X,Y based on the new zone, animating the card to move to that zone.

**Comment by jbauschatz** [comment]
Yes I think that's right.

There should be a separation between the animated card view and the card model itself. 

When a game engine decides to move a card, two things happen. A Card Moved event gets given to the UI for animation, and the card model's new state is persisted. The persistence will probably finish before the animation does, but that is fine because the game engine and model should not know anything about the time it takes to animate.

When a user drags a card (view) from one zone (view) to another, this is translated to a Card Moved event and given to the game's controller. If the controller rejects that event the UI simply snaps the card back where it belongs. If the controller accepts the event it persists the card's new state.
